import type { Metadata, Viewport } from "next";

import { Montserrat, Handlee, Geist } from "next/font/google";

import { Background } from "@/components/Organisms/Background";
import { Footer } from "@/components/Organisms/Footer";
import { ModalProvider } from "@/components/Organisms/ModalProvider";
import { cn } from "@/lib/utils";

import "./globals.css";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const handlee = Handlee({
  variable: "--font-handlee",
  subsets: ["latin"],
  weight: "400",
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        montserrat.variable,
        handlee.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <Background />
        <div className="flex flex-col flex-1 z-0 font-montserrat">
          <main className="flex flex-1">{children}</main>
          <Footer />
          <ModalProvider />
        </div>
      </body>
    </html>
  );
}
