import type { Metadata } from "next";

import { Montserrat, Handlee } from "next/font/google";

import { Background } from "@/components/Organisms/Background";

import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const handlee = Handlee({
  variable: "--font-handlee",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${handlee.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Background />
        <main>{children}</main>
      </body>
    </html>
  );
}
